### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by krosamont** [nischi/MMM-CECControl#14]
Hello,
I have tried to use your module that looks super useful but I get an error that I don't really understand:

```
[18.01.2021 22:21.28.370] [LOG]   Error: Command failed: echo "standby 0" | cec-client RPI -s -d 1
Segmentation fault

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:658:12) {
  killed: false,
  code: 139,
  signal: null,
  cmd: 'echo "standby 0" | cec-client RPI -s -d 1'
}
```

I have installed  ` cec-utils`
I am a bit lost.

Thanks for your help,
Kevin

**Comment by krosamont** [comment]
I was not able to get rid of it so I have replaced in **MMM-CECControlNodeHelper.js** (starting at line 64):
```
  turnOnCEC: function (callback) {
    this.execWrapper(
      'echo "on 0" | cec-client ' + this.config.comport + ' -s -d 1',
      callback
    );
  },

  turnOffCEC: function (callback) {
    this.execWrapper(
      'echo "standby 0" | cec-client ' + this.config.comport + ' -s -d 1',
      callback
    );
  },
```

by 


```
  turnOnCEC: function (callback) {
    this.execWrapper(
      '/opt/vc/bin/tvservice -p && sudo chvt 6 && sudo chvt 7',
      callback
    );
  },

  turnOffCEC: function (callback) {
    this.execWrapper(
      '/opt/vc/bin/tvservice -o,
      callback
    );
  },
```

And it seems to work.

**Comment by nischi** [comment]
Hmm strange, but is this working on every hdmi device? If yes, can you please do a Pull Request for this?

**Comment by krosamont** [comment]
Hey, I can't guarantee that it works on every hdmi device but it should :)
