### ISSUE TITLE
ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by HorstBaerbel** [nischi/MMM-CECControl#9]
When CEC is used, due to naming error: https://github.com/nischi/MMM-CECControl/blob/c55a9ab27d639129de31f894a1f6e43ba8ca3d8c/node_helper.js#L71-L72

**Comment by ericlo00** [comment]
Is this fixed?  I seem to still get the same callback error using CECControl.  Btw, I'm using the latest node_helper.js.

```
[22:41:51.909] [LOG]    CECControl change status (current, new): none on
[22:41:51.911] [LOG]    Whoops! There was an uncaught exception...
[22:41:51.911] [ERROR]  ReferenceError: callback is not defined
    at Class.turnOnCEC (/home/pi/MagicMirror/modules/MMM-CECControl/node_helper.js:70:72)
    at Class.turnOn (/home/pi/MagicMirror/modules/MMM-CECControl/node_helper.js:99:9)
    at Class.handleQueue (/home/pi/MagicMirror/modules/MMM-CECControl/node_helper.js:33:13)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-CECControl/node_helper.js:64:10)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:113:11)
    at Socket.emit (events.js:200:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

```

**Comment by nischi** [comment]
i need to check that on my machine shortly. will get some feedback.

**Comment by HorstBaerbel** [comment]
@nischi Not a node.js expert, but you might need to update package-lock.json to the new version number (1.4). I update the version in package.json, but not in package-lock.json.

**Comment by nischi** [comment]
@HorstBaerbel package-lock.json is a generated file and you should not update it manually. Its anyway not needed if you do a npm install, only if you use npm ci. So that do no difference but should be the same.
